name: CI/CD build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('**/spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/ollama/OllamaImage.java') }}

      - name: Build with Maven and deploy to Artifactory
        run: mvn -s settings.xml -Dfailsafe.rerunFailingTestsCount=4 --batch-mode --update-snapshots verify

